name: Trigger Machine World Rebuild
 
on:
  push:
    branches: [main]
 
jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_mWId2GbjPpMZuOPuczEJlVFJRh8H/tKCJFq73vA"
 
